### ISSUE TITLE
hello,import  error:undefined symbol: PyCObject_Type

### ISSUE THREAD

**Issue by resplendent-star** [ucbdrive/3d-vehicle-tracking#28] opened 2020-04-10 12:18 UTC
(base) lzw@resplendent-star:~/resplendent_code/3d-vehicle-tracking-master/faster-rcnn.pytorch$ ./run_train.sh
Traceback (most recent call last):
  File "trainval_net.py", line 24, in <module>
    from roi_data_layer.roidb import combined_roidb
  File "/home/lzw/resplendent_code/3d-vehicle-tracking-master/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 9, in <module>
    from datasets.factory import get_imdb
  File "/home/lzw/resplendent_code/3d-vehicle-tracking-master/faster-rcnn.pytorch/lib/datasets/factory.py", line 19, in <module>
    from datasets.kitti import kitti
  File "/home/lzw/resplendent_code/3d-vehicle-tracking-master/faster-rcnn.pytorch/lib/datasets/kitti.py", line 11, in <module>
    import cv2
ImportError: /home/lzw/resplendent_code/voxblox_pp_ws/devel/lib/python2.7/dist-packages/cv2.so: undefined symbol: PyCObject_Type
lzw : 201_14_18895 Finish!
(base) lzw@resplendent-star:~/resplendent_code/3d-vehicle-tracking-master/faster-rcnn.pytorch$ 

--------------------------------------------------------------------------------------
one  more thing:the voxblox_pp_ws is another ros code package,but I dont konw why it appear here

**Comment by resplendent-star** [comment] 2020-04-10 12:19
base) lzw@resplendent-star:/resplendent_code/3d-vehicle-tracking-master/faster-rcnn.pytorch$ ./run_train.sh
Traceback (most recent call last):
File "trainval_net.py", line 24, in
from roi_data_layer.roidb import combined_roidb
File "/home/lzw/resplendent_code/3d-vehicle-tracking-master/faster-rcnn.pytorch/lib/roi_data_layer/roidb.py", line 9, in
from datasets.factory import get_imdb
File "/home/lzw/resplendent_code/3d-vehicle-tracking-master/faster-rcnn.pytorch/lib/datasets/factory.py", line 19, in
from datasets.kitti import kitti
File "/home/lzw/resplendent_code/3d-vehicle-tracking-master/faster-rcnn.pytorch/lib/datasets/kitti.py", line 11, in
import cv2
ImportError: /home/lzw/resplendent_code/voxblox_pp_ws/devel/lib/python2.7/dist-packages/cv2.so: undefined symbol: PyCObject_Type
lzw : 201_14_18895 Finish!
(base) lzw@resplendent-star:/resplendent_code/3d-vehicle-tracking-master/faster-rcnn.pytorch$

one more thing:the voxblox_pp_ws is another ros code package,but I dont konw why it appear here

**Comment by resplendent-star** [comment] 2020-04-10 12:19
after  "~/resplendent_code/3d-vehicle-tracking-master/faster-rcnn.pytorch$ ./run_train.sh"

**Comment by eborboihuc** [comment] 2021-06-25 09:14
I'll close this since it seems the problem is solved by the OP.

Just a side note that the path seems to be a) python version is an old 2.7 b) the python seems to be compiled manually for other repo. Please use a clean development environment and check it again.

`voxblox_pp_ws/devel/lib/python2.7/dist-packages/cv2.so: undefined symbol: PyCObject_Type`

**Closed by eborboihuc** 2021-06-25 09:14 UTC
